version: '3'

services:
  pyapp:
    image: mkenjis/my_phpapp
    build: .
    ports:
      - '8000:80'
    deploy:
      replicas: 3
#    volumes:
#      - /root/php_apache_mysql:/var/www/html
    networks:
      - net1
    depends_on:
      - db
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /root/data-dir:/var/lib/mysql
    networks:
      - net1
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  net1:
    driver: overlay
